### ISSUE TITLE
GUI needs some enhancing

### ISSUE THREAD

**Issue by Moppa5** [szopin/harbour-sfos-forum-viewer#2]
**Description**
Firstly, I'd like to thank you for making this app for Sailfish Forum. The app has the basic functionality and works well. However, I would propose that the GUI needs some enhancing since now it's quite hard to read the posts since they don't have too much padding. I'm currently working on with some enhancements on my fork. We could also introduce GUI enhancements to other pages and views.

**Screenshots**
Here are suggestions / screenshots what I've come up this far.

This one would add some more padding to enhance the readability and add a little more block-like look. 
![ss+(2020-07-25+at+12 07 15)](https://user-images.githubusercontent.com/16706187/88453440-8833a880-ce6f-11ea-81bd-ead4d44594f2.jpg)

We could also add separators to the view but not sure if it's any better really
![ss+(image)](http://puu.sh/GaMSd/d757c73640.jpg)

What do you think @szopin? @elros34? Also could you think about giving me push rights to the repo or will I continue to develop on my own fork? We could yet still develop in branches and rebase to master with PRs.

**Comment by szopin** [comment]
Lets see if replying to github emails works as it will take some time to reach a desktop...
PR is probably best, I can get you guys push rights once I get home if that works better. I'm usually trying to avoid too much padding as that can add extra scrolling and cuts on content per page which for me is a minus on phones that already have limited screen real estate (or maybe it's because I'm still stuck on jollaC and not an issue on xperias), that said the changes look great in the screenshot (maybe even <b>oldening of title would make sense, have this currently in my wip  version on phone for search results and it looks ok). Many thanks for your contributions and interest in the project, just make a PR with the version you're happy with and we'll hopefully push it out today (search will have to wait as I'm having a bit of issues with scrolling to right position atm)
Thanks!

On Saturday, 25 July 2020, Santeri wrote:
> **Description**
> Firstly, I'd like to thank you for making this app for Sailfish Forum. The app has the basic functionality and works well. However, I would propose that the GUI needs some enhancing since now it's quite hard to read the posts since they don't have too much padding. I'm currently working on with some enhancements on my fork. We could also introduce GUI enhancements to other pages and views.
> 
> **Screenshots**
> Here are suggestions / screenshots what I've come up this far.
> 
> This one would add some more padding to enhance the readability and add a little more block-like look. 
> ![ss+(2020-07-25+at+12 07 15)](https://user-images.githubusercontent.com/16706187/88453440-8833a880-ce6f-11ea-81bd-ead4d44594f2.jpg)
> 
> What do you think @szopin? @elros34? Also could you think about giving me push rights to the repo or will I continue to develop on my own fork? We could yet still develop in branches and rebase to master with PRs. 
> 
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/

-- 
Sent from my Jolla

**Comment by Moppa5** [comment]
@szopin Thanks for fast reply! I'll get back later in the evening so rolling out today might not be possible. However, I'll make PR from my fork after I'm happy that. Might continue the stuff in the evening and then make PR tomorrow. We'll get back!

**Comment by szopin** [comment]
Awesome, glad to hear email replies work as github is sadly becoming less and less usable with default browser (browsing source recently stopped working which is a huge disappointment) 

On Saturday, 25 July 2020, Santeri wrote:
> @szopin Thanks for fast reply! I'll get back later in the evening so rolling out today might not be possible. However, I'll make PR from my fork after I'm happy that. Might continue the stuff in the evening and then make PR tomorrow. We'll get back!
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/szopin/harbour-sfos-forum-viewer/issues/2#issuecomment-66383756

-- 
Sent from my Jolla
