### ISSUE TITLE
Main icon still not good designed. 

### ISSUE THREAD

**Issue by GNUuser** [szopin/harbour-sfos-forum-viewer#8]
Will cool a better icon.

**Comment by Moppa5** [comment]
@GNUuser Could you elaborate this more? Currently there's no argument or whatsoever on why it's "not good designed". There's no much point making these issues if you don't really work out the information. Please post your ideas or prototypes here so we can see and sort of review and give feedback.

**Comment by szopin** [comment]
Agreed, if you have something to contribute, please do or discuss with the author, he's available for comments and criticisms at openrepos: https://openrepos.net/comment/reply/11114/34380
'Icon bad' adds literally nothing

**Comment by dseight** [comment]
Sorry for commenting on a closed issue, but I think that there is no better place to propose and discuss alternative icon design.

So, I want to propose more "sailfishy" icon (with slightly rounded edges, soft gradient and icon from Silica):

<img width="600" alt="Icon Variants" src="https://user-images.githubusercontent.com/1594949/89167764-7d21fc00-d584-11ea-9de5-bfea95d760b9.png">

All variants use primary Forum color as a background. As for me, the first one fits best: because multi-colored dots are representing colors used on Forum for different categories.

**Comment by szopin** [comment]
Ok, reopened, please vote with idk github emojis I guess, will open a thread on the forum so more people can chime in

**Comment by szopin** [comment]
Ok, posted on forum https://forum.sailfishos.org/t/sfos-forum-viewer-feedback-thread/1317 will have a look if/when people had a chance to look at it, thanks!

**Comment by GNUuser** [comment]
Wow fancy icons. Shut Up And Take My Money! @dseight

**Comment by ferlanero** [comment]
> Sorry for commenting on a closed issue, but I think that there is no better place to propose and discuss alternative icon design.
> 
> So, I want to propose more "sailfishy" icon (with slightly rounded edges, soft gradient and icon from Silica):
> 
> <img alt="Icon Variants" width="600" src="https://user-images.githubusercontent.com/1594949/89167764-7d21fc00-d584-11ea-9de5-bfea95d760b9.png">
> 
> All variants use primary Forum color as a background. As for me, the first one fits best: because multi-colored dots are representing colors used on Forum for different categories.
> 
> SVGs and PNGs: [harbour-sfos-forum-viewer.zip](https://github.com/szopin/harbour-sfos-forum-viewer/files/5016325/harbour-sfos-forum-viewer.zip)

SFV / Colored one looks incredible!

**Comment by szopin** [comment]
> 
> 
> Sorry for commenting on a closed issue, but I think that there is no better place to propose and discuss alternative icon design.
> 
> So, I want to propose more "sailfishy" icon (with slightly rounded edges, soft gradient and icon from Silica):
> 
> <img alt="Icon Variants" width="600" src="https://user-images.githubusercontent.com/1594949/89167764-7d21fc00-d584-11ea-9de5-bfea95d760b9.png">
> 
> All variants use primary Forum color as a background. As for me, the first one fits best: because multi-colored dots are representing colors used on Forum for different categories.
> 
> SVGs and PNGs: [harbour-sfos-forum-viewer.zip](https://github.com/szopin/harbour-sfos-forum-viewer/files/5016325/harbour-sfos-forum-viewer.zip)

Do you have the tricolour one (the left one in this discussion) as an svg? 17:13 is probably not really that huge edge... but the tendency is clear

**Comment by dseight** [comment]
> Do you have the tricolour one (the left one in this discussion) as an svg? 17:13 is probably not really that huge edge... but the tendency is clear

All of the variants in SVG are in attachment to that message ([harbour-sfos-forum-viewer.zip](https://github.com/szopin/harbour-sfos-forum-viewer/files/5016325/harbour-sfos-forum-viewer.zip)).

**Comment by szopin** [comment]
Fixed in 0.7.6

**Comment by dseight** [comment]
> Do you have the discourse-based version in svg format maybe still? Thanks in advance

Sure: [harbour-sfos-forum-viewer-discourse.zip](https://github.com/szopin/harbour-sfos-forum-viewer/files/5117467/harbour-sfos-forum-viewer-discourse.zip)

**Comment by dseight** [comment]
> HI @dseight many peoples are complain with your nice icons already merged in this app, so can you work together with me to replace it for an better forum icon desing please...

People will always complain about something new :) But I can try to make a bit better icon. Indeed, Discourse-like icon seems to be a nice candidate. By the way, do you have any suggestions?

**Comment by GNUuser** [comment]
> People will always complain about something new :) But I can try to make a bit better icon. Indeed, Discourse-like icon seems to be a nice candidate. By the way, do you have any suggestions?
 
Yeah Discourse-like icons is going to the right way, but looks some zoomed. If we want to create a nice icon we need to start from the zero. First we need to find the content that will carry the new icon, then choose the design icon.
![forum-icons](https://user-images.githubusercontent.com/45316884/91106468-b956f280-e640-11ea-919c-e4b96a2742bc.png)

**Comment by dseight** [comment]
> Yeah Discourse-like icons is going to the right way, but looks some zoomed.

What do you mean under "zoomed"? Discourse logo fits perfectly into outline mentioned in [guide](https://sailfishos.org/content/uploads/2018/11/48_SAILFISH-APPS-ICON-STORY.pdf):
<img width="256" alt="Screenshot 2020-08-25 at 03 02 12" src="https://user-images.githubusercontent.com/1594949/91107999-69e3e700-e67f-11ea-9a5f-c865c79819c1.png">

> If we want to create a nice icon we need to start from zero.

Unfortunately, I have no idea to start with (except from some styled message bubbles, as you might have seen above). Do you have any suggestions on main icon idea?

Btw, are icons on picture from some old Sailfish version? At least, I cannot find them in official [Apps icon story](https://sailfishos.org/content/uploads/2018/11/48_SAILFISH-APPS-ICON-STORY.pdf).

**Comment by GNUuser** [comment]
> Btw, are icons on picture from some old Sailfish version? At least, I cannot find them in official [Apps icon story](https://sailfishos.org/content/uploads/2018/11/48_SAILFISH-APPS-ICON-STORY.pdf).

First I am sorry to respond you late, i  am a bit busy.
Zoomed mean the icon is looking for some reason blurred, it could be the colors is not matching between.
There are a lot  of things  to put into an icon forum,  be patient until we find the best metaphors.  
We can start with the message-bubbles from Jolla news blogs forum. Please follow the same desing of this bubbles, you can make 2 or 3 bubles into the icon to simulate an exchange of ideas or messages, please create lot of icons/colors examples then paste here to get feedbacks.
![jollaforo](https://user-images.githubusercontent.com/45316884/91246471-e62d0780-e71d-11ea-9b2e-3bbeb3e6e6ba.jpeg)

**Comment by GNUuser** [comment]
Usually icon designs are SIMPLE, but with very GOOD COLOR CONTRAST. 
MAKE AN ICON WITH 3 BUBBLES or THINGS,  NOT WITH 2 BUBBLES, because 2 bubbles mean 2 person chatting like IM.
Here i give you some examples to put into an icon.. do it how is looking  in the new icon!
![disc](https://user-images.githubusercontent.com/45316884/91250964-432dbb00-e728-11ea-991a-590d89579670.jpg)
This  letters example could be work in a icon of  bubbles of sailfish.
![cartas](https://user-images.githubusercontent.com/45316884/91252259-40809500-e72b-11ea-92a6-5e2f4bf03b5a.jpg)
Also you can create 3 fishes or persons the put in the icon.

**Comment by szopin** [comment]
Thanks @dseight I was actually thinking of using one of those discourse styled icons in Discourser as distinguishing between colored dots and monochrome is bit hard... but seeing you guys are trying to cook something here... Will let you guys figure it out, so we don't end up with too similar icons again (or might just use discourse-dark for now and change it if the new sfv logo is too similar)

**Comment by Olf0** [comment]
Actually, I like the design of the ["tricoloured" **`SFV / Colored`**](https://github.com/szopin/harbour-sfos-forum-viewer/issues/8#issuecomment-667917280) icon just as much as the new [**`discourse-light-with-logo`**](https://github.com/szopin/harbour-sfos-forum-viewer/issues/8#issuecomment-679072672) one: They are both excellently designed icons, from their concept to their implementation.  The other suggested icons score less well, IMO.

### Two aspects to consider
1. **The two favourite icons carry quite different messages**
   - The ["tricoloured" **`SFV / Colored`**](https://github.com/szopin/harbour-sfos-forum-viewer/issues/8#issuecomment-667917280) icon fits generically to "text based communication apps" (except maybe for the colour of the dots, for those who know), ranging from SMS over chat etc. to discussion forum software.
   - The [**`discourse-light-with-logo`**](https://github.com/szopin/harbour-sfos-forum-viewer/issues/8#issuecomment-679072672) icon makes explicit visual references to SailfishOS and (for those who know) to Discourse (and may understand the hint, if they also know that FSO is an Discourse instance; only few, IMO).
   
   Hence please also take into account (aside aesthetics) which aspects of the messages these icons send you consider to be valuable or detrimental.
2. **Optimise `discourse-light-with-logo`**
   Space is almost always a critical aspect when designing icons: The various graphical elements are well visible when designing and evaluating icons (e.g. here, in this issue), but on a phone screen the whole icon is just a miniature version of what you see here.
   Consequently I suggest to use the whole space Jolla reserves for the specific graphical elements (as [visually nicely outlined by @dseight](https://github.com/szopin/harbour-sfos-forum-viewer/issues/8#issuecomment-679428615)): Do pull the tip of the spice extruding from he bubbles to the "south-west" as far into that corner as Jolla allows, in order to make this graphical element (i.e. the spike) slightly more pronounced (and hence better recognisable).
